export const DISTRITOS = [
    { label: "AGALLPAMPA", value: "AGALLPAMPA" },
    { label: "ALONSO DE ALVARADO", value: "ALONSO DE ALVARADO" },
    { label: "ALTO SELVA ALEGRE", value: "ALTO SELVA ALEGRE" },
    { label: "AMARILIS", value: "AMARILIS" },
    { label: "ANCON", value: "ANCON" },
    { label: "ANGASMARCA", value: "ANGASMARCA" },
    { label: "AREQUIPA", value: "AREQUIPA" },
    { label: "ASCOPE", value: "ASCOPE" },
    { label: "ASUNCION", value: "ASUNCION" },
    { label: "ATE", value: "ATE" },
    { label: "ATICO", value: "ATICO" },
    { label: "AUCALLAMA", value: "AUCALLAMA" },
    { label: "AWAJUN", value: "AWAJUN" },
    { label: "AYACUCHO", value: "AYACUCHO" },
    { label: "BAGUA", value: "BAGUA" },
    { label: "BAGUA GRANDE", value: "BAGUA GRANDE" },
    { label: "BAMBAMARCA", value: "BAMBAMARCA" },
    { label: "BARRANCA", value: "BARRANCA" },
    { label: "BARRANQUITA", value: "BARRANQUITA" },
    { label: "BELEN", value: "BELEN" },
    { label: "BELLAVISTA", value: "BELLAVISTA" },
    { label: "BOLIVAR", value: "BOLIVAR" },
    { label: "BREÑA", value: "BREÑA" },
    { label: "BULDIBUYO", value: "BULDIBUYO" },
    { label: "CACHACHI", value: "CACHACHI" },
    { label: "CACHICADAN", value: "CACHICADAN" },
    { label: "CAJABAMBA", value: "CAJABAMBA" },
    { label: "CAJAMARCA", value: "CAJAMARCA" },
    { label: "CAJARURO", value: "CAJARURO" },
    { label: "CALAMARCA", value: "CALAMARCA" },
    { label: "CALCA", value: "CALCA" },
    { label: "CALLAO", value: "CALLAO" },
    { label: "CALLERIA", value: "CALLERIA" },
    { label: "CAMPANILLA", value: "CAMPANILLA" },
    { label: "CARABAMBA", value: "CARABAMBA" },
    { label: "CARABAYLLO", value: "CARABAYLLO" },
    { label: "CARHUAMAYO", value: "CARHUAMAYO" },
    { label: "CASA GRANDE", value: "CASA GRANDE" },
    { label: "CASCAS", value: "CASCAS" },
    { label: "CASMA", value: "CASMA" },
    { label: "CASTILLA", value: "CASTILLA" },
    { label: "CATACAOS", value: "CATACAOS" },
    { label: "CATACHE", value: "CATACHE" },
    { label: "CATILLUC", value: "CATILLUC" },
    { label: "CAYNARACHI", value: "CAYNARACHI" },
    { label: "CAÑARIS", value: "CAÑARIS" },
    { label: "CELENDIN", value: "CELENDIN" },
    { label: "CHACHAPOYAS", value: "CHACHAPOYAS" },
    { label: "CHACLACAYO", value: "CHACLACAYO" },
    { label: "CHADIN", value: "CHADIN" },
    { label: "CHALAMARCA", value: "CHALAMARCA" },
    { label: "CHANCAY", value: "CHANCAY" },
    { label: "CHANCHAMAYO", value: "CHANCHAMAYO" },
    { label: "CHAO", value: "CHAO" },
    { label: "CHARAT", value: "CHARAT" },
    { label: "CHAUPIMARCA", value: "CHAUPIMARCA" },
    { label: "CHAZUTA", value: "CHAZUTA" },
    { label: "CHEPEN", value: "CHEPEN" },
    { label: "CHICAMA", value: "CHICAMA" },
    { label: "CHICLAYO", value: "CHICLAYO" },
    { label: "CHILLIA", value: "CHILLIA" },
    { label: "CHIMBOTE", value: "CHIMBOTE" },
    { label: "CHINCHA ALTA", value: "CHINCHA ALTA" },
    { label: "CHIRIMOTO", value: "CHIRIMOTO" },
    { label: "CHOCOPE", value: "CHOCOPE" },
    { label: "CHOLON", value: "CHOLON" },
    { label: "CHONGOYAPE", value: "CHONGOYAPE" },
    { label: "CHONTABAMBA", value: "CHONTABAMBA" },
    { label: "CHORRILLOS", value: "CHORRILLOS" },
    { label: "CHOTA", value: "CHOTA" },
    { label: "CHUGAY", value: "CHUGAY" },
    { label: "CHULUCANAS", value: "CHULUCANAS" },
    { label: "COCHORCO", value: "COCHORCO" },
    { label: "COISHCO", value: "COISHCO" },
    { label: "COMAS", value: "COMAS" },
    { label: "CONCHUCOS", value: "CONCHUCOS" },
    { label: "CONDEBAMBA", value: "CONDEBAMBA" },
    { label: "CONDORMARCA", value: "CONDORMARCA" },
    { label: "CONTUMAZA", value: "CONTUMAZA" },
    { label: "CORRALES", value: "CORRALES" },
    { label: "CULEBRAS", value: "CULEBRAS" },
    { label: "CURGOS", value: "CURGOS" },
    { label: "CUTERVO", value: "CUTERVO" },
    { label: "CUÑUMBUQUI", value: "CUÑUMBUQUI" },
    { label: "EL AGUSTINO", value: "EL AGUSTINO" },
    { label: "EL CENEPA", value: "EL CENEPA" },
    { label: "EL MILAGRO", value: "EL MILAGRO" },
    { label: "EL PORVENIR", value: "EL PORVENIR" },
    { label: "EL PRADO", value: "EL PRADO" },
    { label: "EL TAMBO", value: "EL TAMBO" },
    { label: "ELIAS SOPLIN VARGAS", value: "ELIAS SOPLIN VARGAS" },
    { label: "ENCAÑADA", value: "ENCAÑADA" },
    { label: "ESPINAR", value: "ESPINAR" },
    { label: "ETEN", value: "ETEN" },
    { label: "FLORENCIA DE MORA", value: "FLORENCIA DE MORA" },
    { label: "GREGORIO PITA", value: "GREGORIO PITA" },
    { label: "GUADALUPE", value: "GUADALUPE" },
    { label: "GUADALUPITO", value: "GUADALUPITO" },
    { label: "HERMILIO VALDIZAN", value: "HERMILIO VALDIZAN" },
    { label: "HUACHO", value: "HUACHO" },
    { label: "HUACRACHUCO", value: "HUACRACHUCO" },
    { label: "HUALGAYOC", value: "HUALGAYOC" },
    { label: "HUALHUAS", value: "HUALHUAS" },
    { label: "HUAMACHUCO", value: "HUAMACHUCO" },
    { label: "HUANCABAMBA", value: "HUANCABAMBA" },
    { label: "HUANCANE", value: "HUANCANE" },
    { label: "HUANCAPI", value: "HUANCAPI" },
    { label: "HUALHUAS", value: "HUALHUAS" },
    { label: "HUAMACHUCO", value: "HUAMACHUCO" },
    { label: "HUANCABAMBA", value: "HUANCABAMBA" },
    { label: "HUANCANE", value: "HUANCANE" },
    { label: "HUANCAPI", value: "HUANCAPI" },
    { label: "HUANCASPATA", value: "HUANCASPATA" },
    { label: "HUANCHACO", value: "HUANCHACO" },
    { label: "HUANTA", value: "HUANTA" },
    { label: "HUANUCO", value: "HUANUCO" },
    { label: "HUARAL", value: "HUARAL" },
    { label: "HUARANCHAL", value: "HUARANCHAL" },
    { label: "HUARAZ", value: "HUARAZ" },
    { label: "HUARMACA", value: "HUARMACA" },
    { label: "HUARMEY", value: "HUARMEY" },
    { label: "HUASAHUASI", value: "HUASAHUASI" },
    { label: "HUASMIN", value: "HUASMIN" },
    { label: "HUASO", value: "HUASO" },
    { label: "HUAYLILLAS", value: "HUAYLILLAS" },
    { label: "HUAYLLABAMBA", value: "HUAYLLABAMBA" },
    { label: "HUAYO", value: "HUAYO" },
    { label: "ICA", value: "ICA" },
    { label: "ILO", value: "ILO" },
    { label: "IMAZA", value: "IMAZA" },
    { label: "INDEPENDENCIA", value: "INDEPENDENCIA" },
    { label: "IQUITOS", value: "IQUITOS" },
    { label: "JAEN", value: "JAEN" },
    { label: "JAYANCA", value: "JAYANCA" },
    { label: "JEQUETEPEQUE", value: "JEQUETEPEQUE" },
    { label: "JESUS", value: "JESUS" },
    { label: "JESUS MARIA", value: "JESUS MARIA" },
    { label: "JOSE CRESPO Y CASTILLO", value: "JOSE CRESPO Y CASTILLO" },
    { label: "JOSE LEONARDO ORTIZ", value: "JOSE LEONARDO ORTIZ" },
    { label: "JOSE MANUEL QUIROZ", value: "JOSE MANUEL QUIROZ" },
    { label: "JOSE SABOGAL", value: "JOSE SABOGAL" },
    { label: "JUANJUI", value: "JUANJUI" },
    { label: "JULCAN", value: "JULCAN" },
    { label: "JULIACA", value: "JULIACA" },
    { label: "LA ARENA", value: "LA ARENA" },
    { label: "LA BANDA DE SHILCAYO", value: "LA BANDA DE SHILCAYO" },
    { label: "LA CUESTA", value: "LA CUESTA" },
    { label: "LA ESPERANZA", value: "LA ESPERANZA" },
    { label: "LA FLORIDA", value: "LA FLORIDA" },
    { label: "LA LIBERTAD DE PALLAN", value: "LA LIBERTAD DE PALLAN" },
    { label: "LA MOLINA", value: "LA MOLINA" },
    { label: "LA PECA", value: "LA PECA" },
    { label: "LA RAMADA", value: "LA RAMADA" },
    { label: "LA UNION", value: "LA UNION" },
    { label: "LA VICTORIA", value: "LA VICTORIA" },
    { label: "LABERINTO", value: "LABERINTO" },
    { label: "LAGUNAS", value: "LAGUNAS" },
    { label: "LAMBAYEQUE", value: "LAMBAYEQUE" },
    { label: "LAREDO", value: "LAREDO" },
    { label: "LAS AMAZONAS", value: "LAS AMAZONAS" },
    { label: "LAS PIRIAS", value: "LAS PIRIAS" },
    { label: "LIMA", value: "LIMA" },
    { label: "LINCE", value: "LINCE" },
    { label: "LLACANORA", value: "LLACANORA" },
    { label: "LLAPA", value: "LLAPA" },
    { label: "LONGOTEA", value: "LONGOTEA" },
    { label: "LONYA GRANDE", value: "LONYA GRANDE" },
    { label: "LOS BAÑOS DEL INCA", value: "LOS BAÑOS DEL INCA" },
    { label: "LOS OLIVOS", value: "LOS OLIVOS" },
    { label: "LUCMA", value: "LUCMA" },
    { label: "LURIGANCHO", value: "LURIGANCHO" },
    { label: "LURIN", value: "LURIN" },
    { label: "MACHE", value: "MACHE" },
    { label: "MAGDALENA", value: "MAGDALENA" },
    { label: "MAGDALENA DE CAO", value: "MAGDALENA DE CAO" },
    { label: "MAGDALENA DEL MAR", value: "MAGDALENA DEL MAR" },
    { label: "MANANTAY", value: "MANANTAY" },
    { label: "MANUEL ANTONIO MESONES MU", value: "MANUEL ANTONIO MESONES MU" },
    { label: "MARCABAL", value: "MARCABAL" },
    { label: "MARCAVELICA", value: "MARCAVELICA" },
    { label: "MARMOT", value: "MARMOT" },
    { label: "MAZAMARI", value: "MAZAMARI" },
    { label: "MIGUEL IGLESIAS", value: "MIGUEL IGLESIAS" },
    { label: "MIRAFLORES", value: "MIRAFLORES" },
    { label: "MOCHE", value: "MOCHE" },
    { label: "MOLLEBAMBA", value: "MOLLEBAMBA" },
    { label: "MOLLEPATA", value: "MOLLEPATA" },
    { label: "MONSEFU", value: "MONSEFU" },
    { label: "MOQUEGUA", value: "MOQUEGUA" },
    { label: "MORROPE", value: "MORROPE" },
    { label: "MOYOBAMBA", value: "MOYOBAMBA" },
    { label: "NAMORA", value: "NAMORA" },
    { label: "NEPEÑA", value: "NEPEÑA" },
    { label: "NIEVA", value: "NIEVA" },
    { label: "NUEVA CAJAMARCA", value: "NUEVA CAJAMARCA" },
    { label: "NUEVO CHIMBOTE", value: "NUEVO CHIMBOTE" },
    { label: "OCALLI", value: "OCALLI" },
    { label: "ONGON", value: "ONGON" },
    { label: "OTUZCO", value: "OTUZCO" },
    { label: "PACANGA", value: "PACANGA" },
    { label: "PACASMAYO", value: "PACASMAYO" },
    { label: "PACHACAMAC", value: "PACHACAMAC" },
    { label: "PADRE ABAD", value: "PADRE ABAD" },
    { label: "PAIJAN", value: "PAIJAN" },
    { label: "PALCAZÚ", value: "PALCAZÚ" },
    { label: "PARCOY", value: "PARCOY" },
    { label: "PARAMONGA", value: "PARAMONGA" },
    { label: "PATAPO", value: "PATAPO" },
    { label: "PATIVILCA", value: "PATIVILCA" },
    { label: "PICSI", value: "PICSI" },
    { label: "PIEROLA", value: "PIEROLA" },
    { label: "PIMENTEL", value: "PIMENTEL" },
    { label: "PINRA", value: "PINRA" },
    { label: "PIRHUA", value: "PIRHUA" },
    { label: "PIURA", value: "PIURA" },
    { label: "PLACERES", value: "PLACERES" },
    { label: "POMACOCHAS", value: "POMACOCHAS" },
    { label: "POROTO", value: "POROTO" },
    { label: "PORRAS", value: "PORRAS" },
    { label: "PUCALA", value: "PUCALA" },
    { label: "PUCALLPA", value: "PUCALLPA" },
    { label: "PUENTE PIEDRA", value: "PUENTE PIEDRA" },
    { label: "PUENTE QUINUA", value: "PUENTE QUINUA" },
    { label: "PUEBLO NUEVO", value: "PUEBLO NUEVO" },
    { label: "PUEBLO NUEVO DE COLAN", value: "PUEBLO NUEVO DE COLAN" },
    { label: "PUEBLO VIEJO", value: "PUEBLO VIEJO" },
    { label: "PUENTE MALPARTIDA", value: "PUENTE MALPARTIDA" },
    { label: "PULLO", value: "PULLO" },
    { label: "QUEROCOTILLO", value: "QUEROCOTILLO" },
    { label: "QUILCA", value: "QUILCA" },
    { label: "QUILLABAMBA", value: "QUILLABAMBA" },
    { label: "QUIRUVILCA", value: "QUIRUVILCA" },
    { label: "QUITO ARMA", value: "QUITO ARMA" },
    { label: "RAYMONDI", value: "RAYMONDI" },
    { label: "RUPA RUPA", value: "RUPA RUPA" },
    { label: "SACOCHE", value: "SACOCHE" },
    { label: "SALAVERRY", value: "SALAVERRY" },
    { label: "SALPO", value: "SALPO" },
    { label: "SAMBA DE MONTERO", value: "SAMBA DE MONTERO" },
    { label: "SAN AGUSTIN", value: "SAN AGUSTIN" },
    { label: "SAN ANTONIO", value: "SAN ANTONIO" },
    { label: "SAN BARTOLO", value: "SAN BARTOLO" },
    { label: "SAN BERNARDO", value: "SAN BERNARDO" },
    { label: "SAN BORJA", value: "SAN BORJA" },
    { label: "SAN CARLOS", value: "SAN CARLOS" },
    { label: "SAN CRISTOBAL", value: "SAN CRISTOBAL" },
    { label: "SAN IGNACIO", value: "SAN IGNACIO" },
    { label: "SAN ISIDRO", value: "SAN ISIDRO" },
    { label: "SAN JOSE", value: "SAN JOSE" },
    { label: "SAN JUAN", value: "SAN JUAN" },
    { label: "SAN JUAN BAUTISTA", value: "SAN JUAN BAUTISTA" },
    { label: "SAN JUAN DE LA VIRGEN", value: "SAN JUAN DE LA VIRGEN" },
    { label: "SAN JUAN DE LURIGANCHO", value: "SAN JUAN DE LURIGANCHO" },
    { label: "SAN JUAN DE MIRAFLORES", value: "SAN JUAN DE MIRAFLORES" },
    { label: "SAN JUAN DE PUCARA", value: "SAN JUAN DE PUCARA" },
    { label: "SAN LUIS", value: "SAN LUIS" },
    { label: "SAN MARTIN", value: "SAN MARTIN" },
    { label: "SAN MARTIN DE PORRES", value: "SAN MARTIN DE PORRES" },
    { label: "SAN MIGUEL", value: "SAN MIGUEL" },
    { label: "SAN NICOLAS", value: "SAN NICOLAS" },
    { label: "SAN PEDRO", value: "SAN PEDRO" },
    { label: "SAN RAMON", value: "SAN RAMON" },
    { label: "SANTA", value: "SANTA" },
    { label: "SANTA ANA", value: "SANTA ANA" },
    { label: "SANTA ANITA", value: "SANTA ANITA" },
    { label: "SANTA CATALINA DE MOSSA", value: "SANTA CATALINA DE MOSSA" },
    { label: "SANTA CRUZ", value: "SANTA CRUZ" },
    { label: "SANTA ELENA", value: "SANTA ELENA" },
    { label: "SANTA LUISA", value: "SANTA LUISA" },
    { label: "SANTA MARIA", value: "SANTA MARIA" },
    { label: "SANTA ROSA", value: "SANTA ROSA" },
    { label: "SANTIAGO", value: "SANTIAGO" },
    { label: "SICCHEZ", value: "SICCHEZ" },
    { label: "SINSICAP", value: "SINSICAP" },
    { label: "SOCOTA", value: "SOCOTA" },
    { label: "SOLRADAS", value: "SOLRADAS" },
    { label: "SORITOR", value: "SORITOR" },
    { label: "SOTILLO", value: "SOTILLO" },
    { label: "SUBTANJALLA", value: "SUBTANJALLA" },
    { label: "SULLANA", value: "SULLANA" },
    { label: "SURCO", value: "SURCO" },
    { label: "SURQUILLO", value: "SURQUILLO" },
    { label: "TACABAMBA", value: "TACABAMBA" },
    { label: "TACNA", value: "TACNA" },
    { label: "TALAVERA", value: "TALAVERA" },
    { label: "TALENTINOS", value: "TALENTINOS" },
    { label: "TAMBILLO", value: "TAMBILLO" },
    { label: "TAMBO GRANDE", value: "TAMBO GRANDE" },
    { label: "TAMBO RIO", value: "TAMBO RIO" },
    { label: "TARAPOTO", value: "TARAPOTO" },
    { label: "TARICA", value: "TARICA" },
    { label: "TARMA", value: "TARMA" },
    {
        label: "TENIENTE CESAR LOPEZ ROJAS",
        value: "TENIENTE CESAR LOPEZ ROJAS",
    },
    { label: "TILIVIQUE", value: "TILIVIQUE" },
    { label: "TINTAY", value: "TINTAY" },
    { label: "TIRINGO", value: "TIRINGO" },
    { label: "TOCACHE", value: "TOCACHE" },
    { label: "TOMBO", value: "TOMBO" },
    { label: "TOMINA", value: "TOMINA" },
    { label: "TORIBIO CASANOVA", value: "TORIBIO CASANOVA" },
    { label: "TOTORACOCHA", value: "TOTORACOCHA" },
    { label: "TOTOS", value: "TOTOS" },
    { label: "TRUJILLO", value: "TRUJILLO" },
    { label: "TUCUME", value: "TUCUME" },
    { label: "TUMAN", value: "TUMAN" },
    { label: "TUMBES", value: "TUMBES" },
    { label: "TUMI", value: "TUMI" },
    { label: "TURBO", value: "TURBO" },
    { label: "UCUBAMBA", value: "UCUBAMBA" },
    { label: "URUBAMBA", value: "URUBAMBA" },
    { label: "VILLA EL SALVADOR", value: "VILLA EL SALVADOR" },
    { label: "VILLA MARIA DEL TRIUNFO", value: "VILLA MARIA DEL TRIUNFO" },
    { label: "VILLA RICA", value: "VILLA RICA" },
    { label: "VILLACURI", value: "VILLACURI" },
    { label: "VILLOZA", value: "VILLOZA" },
    { label: "VIRACO", value: "VIRACO" },
    { label: "VIRU", value: "VIRU" },
    { label: "VISTA ALEGRE", value: "VISTA ALEGRE" },
    { label: "YANAC", value: "YANAC" },
    { label: "YANAHUARA", value: "YANAHUARA" },
    { label: "YANTALO", value: "YANTALO" },
    { label: "YARINACOCHA", value: "YARINACOCHA" },
    { label: "YAUYA", value: "YAUYA" },
    { label: "YONAN", value: "YONAN" },
    { label: "YURIMAGUAS", value: "YURIMAGUAS" },
    { label: "YUSCA", value: "YUSCA" },
    { label: "ZARUMILLA", value: "ZARUMILLA" },
];